### ISSUE TITLE
Just to keep in mind when upgrading to Airflow==1.10.5

### ISSUE THREAD

**Issue by michael-kotliar** [datirium/scidap#5]
Airflow uses `default_pool` for all DAGs if it wasn't set.
```WARNING - Tasks using non-existent pool 'default_pool' will not be scheduled```

**Comment by Taxuspt** [comment]
> Airflow uses `default_pool` for all DAGs if it wasn't set.
> `WARNING - Tasks using non-existent pool 'default_pool' will not be scheduled`

Bumped into this problem after upgrading, solved it by creating a `default_pool` with

`airflow pool -s default_pool 128 'default pool'`

**Comment by jmagana2000** [comment]
OMG. I just upgraded airflow to 1.10.5 and was Freaking out that my jobs were not executing. You Rock!

**Comment by portah** [comment]
I hope everybody learned the lesson :)
